package com.vibrations.vibrationsapi.model;

import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.List;

@Entity
@Data
@NoArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(name = "profile_picture_link")
    private String profilePictureLink;
    @Column(name = "email")
    private String email;
    @Column(name = "phone_number")
    private Long phoneNumber;
    @Column(name = "password")
    private String password;
    @Column(name = "fav_song")
    private List<String> favSong;
    @Column(name = "fav_artist")
    private List<String> favArtist;
    @Column(name = "fav_genre")
    private List<String> favGenre;
    @Column(name = "score")
    private double score;
    @Column(name = "latitude")
    private double latitude;
    @Column(name = "longitude")
    private double longitude;
    //@ManyToMany
    //private List<User> matches;



    // Constructors are generated by Lombok
}
