package com.vibrations.vibrationsapi.model;

import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.List;

@Entity
@Data
@NoArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String firstName;
    private String lastName;
    private String profilePictureLink;
    private String email;
    private int phoneNumber;
    private String password;
    private String favSong;
    private String favArtist;
    private String favGenre;

    @ManyToMany
    private List<User> matches;

    private double score;

    // Constructors are generated by Lombok
}
