package com.vibrations.vibrationsapi.model;

import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.List;

@Entity
@Data
@NoArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String firstName;
    private String lastName;
    private String profilePictureLink;
    private String email;
    private Long phoneNumber;
    private String password;
    private List<String> favSong;
    private List<String> favArtist;
    private List<String> favGenre;
    private double score;
    private double latitude;
    private double longitude;
    //@ManyToMany
    //private List<User> matches;



    // Constructors are generated by Lombok
}
